name = "wine-frontend"
main = "workers-site/index.js"
compatibility_date = "2024-01-01"

[site]
bucket = "./dist"

[vars]
# URL бэкенда API (основной воркер)
API_URL = "https://telegram-wine-bot.2gc.workers.dev"

# Домен для фронтенда
FRONTEND_URL = "https://wine-app.2gc.ru"

# Кастомный домен
[[routes]]
pattern = "wine-app.2gc.ru/*"
zone_name = "2gc.ru" 