name = "telegram-wine-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# URL для webhook (Cloudflare Workers URL)
WORKER_URL = "https://telegram-wine-bot.2gc.workers.dev"
# Эти переменные будут установлены через wrangler secret
# TELEGRAM_BOT_TOKEN
# GOOGLE_SHEETS_API_KEY
# GOOGLE_SHEETS_SPREADSHEET_ID
# GOOGLE_SHEETS_COCKTAIL_SPREADSHEET_ID (ID документа с коктейлями)
# CLOUDFLARE_ACCOUNT_ID (для ИИ)
# CLOUDFLARE_AI_TOKEN (для ИИ)

[[kv_namespaces]]
binding = "WINE_CACHE"
id = "e7107413f4a7434a8e9d101b337dc5d4"
preview_id = "97d3cb4a1aee4074b673f3ad3e057375" 