name = "telegram-wine-bot"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
# URL для webhook (Cloudflare Workers URL)
WORKER_URL = "https://telegram-wine-bot.2gc.workers.dev"
# Эти переменные будут установлены через wrangler secret
# TELEGRAM_BOT_TOKEN
# GOOGLE_SHEETS_API_KEY
# GOOGLE_SHEETS_SPREADSHEET_ID
# GOOGLE_SHEETS_COCKTAIL_SPREADSHEET_ID (ID документа с коктейлями)
# CLOUDFLARE_ACCOUNT_ID (для ИИ)
# CLOUDFLARE_AI_TOKEN (для ИИ)

[[kv_namespaces]]
binding = "WINE_CACHE"
id = "e7107413f4a7434a8e9d101b337dc5d4"
preview_id = "97d3cb4a1aee4074b673f3ad3e057375"

[[d1_databases]]
binding = "DB"
database_name = "wine-bot-db"
database_id = "4de41da1-d801-4e91-ab74-5107b445fb05" 

[triggers]
crons = [
  "00 06 * * *",  # 09:00 МСК
  "00 19 * * *"   # 22:00 МСК
]
# Каждый день в 12:00 и 18:00 по Москве (МСК, UTC+3) 

[env.admin]
name = "telegram-wine-bot-admin"
main = "src/admin-bot.js"
compatibility_date = "2024-01-01"

# База данных для админ-бота (использует ту же базу)
[[env.admin.d1_databases]]
binding = "DB"
database_name = "wine-bot-db"
database_id = "4de41da1-d801-4e91-ab74-5107b445fb05"

# Кэш для админ-бота (использует тот же кэш)
[[env.admin.kv_namespaces]]
binding = "WINE_CACHE"
id = "e7107413f4a7434a8e9d101b337dc5d4"
preview_id = "97d3cb4a1aee4074b673f3ad3e057375"

# Переменные для админ-бота
[env.admin.vars]
WORKER_URL = "https://telegram-wine-bot-admin.2gc.workers.dev"
migrations_dir = "./migrations"
